movie_dict = [
    {"title": "Inception", "genres": ["Action", "Sci-Fi", "Thriller"], "duration": 148, "rating": 8.8},
    {"title": "The Shawshank Redemption", "genres": ["Drama"], "duration": 142, "rating": 9.3},
    {"title": "The Dark Knight", "genres": ["Action", "Crime", "Drama"], "duration": 152, "rating": 9.0},
    {"title": "Pulp Fiction", "genres": ["Crime", "Drama"], "duration": 154, "rating": 8.9},
    {"title": "The Godfather", "genres": ["Crime", "Drama"], "duration": 175, "rating": 9.2},
    {"title": "The Matrix", "genres": ["Action", "Sci-Fi"], "duration": 136, "rating": 8.7},
    {"title": "Interstellar", "genres": ["Adventure", "Drama", "Sci-Fi"], "duration": 169, "rating": 8.6},
    {"title": "Forrest Gump", "genres": ["Drama", "Romance"], "duration": 142, "rating": 8.8},
    {"title": "Parasite", "genres": ["Comedy", "Drama", "Thriller"], "duration": 132, "rating": 8.6},
    {"title": "Gladiator", "genres": ["Action", "Adventure", "Drama"], "duration": 155, "rating": 8.5},
    {"title": "Mad Max: Fury Road", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 120, "rating": 8.1},
    {"title": "Fight Club", "genres": ["Drama"], "duration": 139, "rating": 8.8},
    {"title": "The Grand Budapest Hotel", "genres": ["Adventure", "Comedy", "Drama"], "duration": 99, "rating": 8.1},
    {"title": "Joker", "genres": ["Crime", "Drama", "Thriller"], "duration": 122, "rating": 8.4},
    {"title": "Spirited Away", "genres": ["Animation", "Adventure", "Family"], "duration": 125, "rating": 8.6},
    {"title": "Coco", "genres": ["Animation", "Adventure", "Family"], "duration": 105, "rating": 8.4},
    {"title": "Avengers: Endgame", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 181, "rating": 8.4},
    {"title": "Schindler's List", "genres": ["Biography", "Drama", "History"], "duration": 195, "rating": 9.0},
    {"title": "Whiplash", "genres": ["Drama", "Music"], "duration": 107, "rating": 8.5},
    {"title": "Toy Story", "genres": ["Animation", "Adventure", "Comedy"], "duration": 81, "rating": 8.3},
    {"title": "The Lion King", "genres": ["Animation", "Adventure", "Drama"], "duration": 88, "rating": 8.5},
    {"title": "Finding Nemo", "genres": ["Animation", "Adventure", "Comedy"], "duration": 100, "rating": 8.2},
    {"title": "Up", "genres": ["Animation", "Adventure", "Comedy"], "duration": 96, "rating": 8.3},
    {"title": "Crazy Rich Asians", "genres": ["Comedy", "Romance"], "duration": 120, "rating": 6.9},
    {"title": "How to Lose a Guy in 10 Days", "genres": ["Comedy", "Romance"], "duration": 116, "rating": 6.4},
    {"title": "La La Land", "genres": ["Comedy", "Drama", "Music"], "duration": 128, "rating": 8.0},
    {"title": "The Pursuit of Happyness", "genres": ["Biography", "Drama"], "duration": 117, "rating": 8.0},
    {"title": "A Star Is Born", "genres": ["Drama", "Music", "Romance"], "duration": 136, "rating": 7.6},
    {"title": "The Social Network", "genres": ["Biography", "Drama"], "duration": 120, "rating": 7.7},
    {"title": "Good Will Hunting", "genres": ["Drama"], "duration": 126, "rating": 8.3},
    {"title": "The Wolf of Wall Street", "genres": ["Biography", "Comedy", "Crime"], "duration": 180, "rating": 8.2},
    {"title": "Black Swan", "genres": ["Drama", "Thriller"], "duration": 108, "rating": 8.0},
    {"title": "The Revenant", "genres": ["Action", "Adventure", "Drama"], "duration": 156, "rating": 8.0},
    {"title": "Django Unchained", "genres": ["Drama", "Western"], "duration": 165, "rating": 8.4},
    {"title": "No Country for Old Men", "genres": ["Crime", "Drama", "Thriller"], "duration": 122, "rating": 8.2},
    {"title": "The Irishman", "genres": ["Biography", "Crime", "Drama"], "duration": 209, "rating": 7.8},
    {"title": "The Green Mile", "genres": ["Crime", "Drama", "Fantasy"], "duration": 189, "rating": 8.6},
    {"title": "The Prestige", "genres": ["Drama", "Mystery", "Sci-Fi"], "duration": 130, "rating": 8.5},
    {"title": "Blade Runner 2049", "genres": ["Action", "Drama", "Sci-Fi"], "duration": 164, "rating": 8.0},
    {"title": "Dune", "genres": ["Action", "Adventure", "Drama"], "duration": 155, "rating": 8.3},
    {"title": "Everything Everywhere All at Once", "genres": ["Action", "Adventure", "Comedy"], "duration": 139, "rating": 8.0},
    {"title": "The Batman", "genres": ["Action", "Crime", "Drama"], "duration": 176, "rating": 7.9},
    {"title": "Oppenheimer", "genres": ["Biography", "Drama", "History"], "duration": 180, "rating": 8.4},
    {"title": "Barbie", "genres": ["Adventure", "Comedy", "Fantasy"], "duration": 114, "rating": 7.0},
    {"title": "Knives Out", "genres": ["Comedy", "Crime", "Drama"], "duration": 130, "rating": 7.9},
    {"title": "Glass Onion", "genres": ["Comedy", "Crime", "Drama"], "duration": 139, "rating": 7.1},
    {"title": "Get Out", "genres": ["Horror", "Mystery", "Thriller"], "duration": 104, "rating": 7.7},
    {"title": "A Quiet Place", "genres": ["Drama", "Horror", "Sci-Fi"], "duration": 90, "rating": 7.5},
    {"title": "The Conjuring", "genres": ["Horror", "Mystery", "Thriller"], "duration": 112, "rating": 7.5},
    {"title": "Hereditary", "genres": ["Drama", "Horror", "Mystery"], "duration": 127, "rating": 7.3},
    {"title": "It", "genres": ["Horror", "Thriller"], "duration": 135, "rating": 7.3},
    {"title": "The Exorcist", "genres": ["Horror"], "duration": 122, "rating": 8.0},
    {"title": "Jaws", "genres": ["Adventure", "Thriller"], "duration": 124, "rating": 8.1},
    {"title": "Shutter Island", "genres": ["Mystery", "Thriller"], "duration": 138, "rating": 8.2},
    {"title": "Logan", "genres": ["Action", "Drama", "Sci-Fi"], "duration": 137, "rating": 8.1},
    {"title": "Deadpool", "genres": ["Action", "Adventure", "Comedy"], "duration": 108, "rating": 8.0},
    {"title": "Guardians of the Galaxy", "genres": ["Action", "Adventure", "Comedy"], "duration": 121, "rating": 8.0},
    {"title": "Doctor Strange", "genres": ["Action", "Adventure", "Fantasy"], "duration": 115, "rating": 7.5},
    {"title": "Black Panther", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 134, "rating": 7.3},
    {"title": "Thor: Ragnarok", "genres": ["Action", "Adventure", "Comedy"], "duration": 130, "rating": 7.9},
    {"title": "Iron Man", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 126, "rating": 7.9},
    {"title": "Captain America: The Winter Soldier", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 136, "rating": 7.8},
    {"title": "The Avengers", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 143, "rating": 8.0},
    {"title": "Spider-Man: Into the Spider-Verse", "genres": ["Animation", "Action", "Adventure"], "duration": 117, "rating": 8.4},
    {"title": "Casablanca", "genres": ["Drama", "Romance", "War"], "duration": 102, "rating": 8.5},
    {"title": "Gone with the Wind", "genres": ["Drama", "History", "Romance"], "duration": 238, "rating": 8.1},
    {"title": "Citizen Kane", "genres": ["Drama", "Mystery"], "duration": 119, "rating": 8.3},
    {"title": "Psycho", "genres": ["Horror", "Mystery", "Thriller"], "duration": 109, "rating": 8.5},
    {"title": "Rear Window", "genres": ["Mystery", "Thriller"], "duration": 112, "rating": 8.4},
    {"title": "Tenet", "genres": ["Action", "Sci-Fi", "Thriller"], "duration": 150, "rating": 7.3},
    {"title": "Arrival", "genres": ["Drama", "Mystery", "Sci-Fi"], "duration": 116, "rating": 7.9},
    {"title": "Edge of Tomorrow", "genres": ["Action", "Adventure", "Sci-Fi"], "duration": 113, "rating": 7.9},
    {"title": "Ex Machina", "genres": ["Drama", "Sci-Fi", "Thriller"], "duration": 108, "rating": 7.7},
    {"title": "The Martian", "genres": ["Adventure", "Drama", "Sci-Fi"], "duration": 144, "rating": 8.0},
    {"title": "The Babadook", "genres": ["Drama", "Horror", "Thriller"], "duration": 94, "rating": 6.8},
    {"title": "Midsommar", "genres": ["Drama", "Horror", "Mystery"], "duration": 148, "rating": 7.1},
    {"title": "The Hangover", "genres": ["Comedy"], "duration": 100, "rating": 7.7},
    {"title": "Superbad", "genres": ["Comedy"], "duration": 113, "rating": 7.6},
    {"title": "Step Brothers", "genres": ["Comedy"], "duration": 98, "rating": 6.9},
    {"title": "Dumb and Dumber", "genres": ["Comedy"], "duration": 107, "rating": 7.3},
    {"title": "Anchorman", "genres": ["Comedy"], "duration": 94, "rating": 7.2},
    {"title": "500 Days of Summer", "genres": ["Comedy", "Drama", "Romance"], "duration": 95, "rating": 7.7},
    {"title": "The Notebook", "genres": ["Drama", "Romance"], "duration": 123, "rating": 7.8},
    {"title": "Me Before You", "genres": ["Drama", "Romance"], "duration": 110, "rating": 7.4},
    {"title": "Love Actually", "genres": ["Comedy", "Drama", "Romance"], "duration": 135, "rating": 7.6},
    {"title": "Crazy, Stupid, Love", "genres": ["Comedy", "Drama", "Romance"], "duration": 118, "rating": 7.4},
    {"title": "Se7en", "genres": ["Crime", "Drama", "Mystery"], "duration": 127, "rating": 8.6},
    {"title": "American Psycho", "genres": ["Crime", "Drama", "Horror"], "duration": 102, "rating": 7.6},
    {"title": "Oldboy", "genres": ["Action", "Drama", "Mystery"], "duration": 120, "rating": 8.3},
    {"title": "Prisoners", "genres": ["Crime", "Drama", "Mystery"], "duration": 153, "rating": 8.1},
    {"title": "Nightcrawler", "genres": ["Crime", "Drama", "Thriller"], "duration": 117, "rating": 7.8}


]


genre_list = [
    'Action', 
    'Sci-Fi', 'Thriller', 'Drama', 'Crime', 'Adventure', 
    'Romance', 'Comedy', 'Animation', 'Family', 'Biography', 'Horror', 'History', 
    'Music', 'Mystery'
]
